# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Deploy Website
        uses: and-fm/cloudflared-ssh-action@v2.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          private_key: ${{secrets.SSH_KEY}}

          commands: |
            echo 'delete file lama yang udah ada dissh' 
            echo "${{secrets.SSH_PASSWORD}}" | sudo -S rm -rf Spotify-Clone
            echo ' NARIK FILE DARI GITHUB '
            git clone git@github.com:ArkanWiryaS/Spotify-Clone.git
            cd Spotify-Clone
            cd backend
            echo "${{secrets.BACKEND_ENV}}" >> .env
            cd ..
            npm run build
            pm2 start ecosystem.config.js
            echo 'service started'
            exit
            
